// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PulsarDataIngestionClient is the client API for PulsarDataIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PulsarDataIngestionClient interface {
	Ingest(ctx context.Context, in *Beacons, opts ...grpc.CallOption) (*IngestResult, error)
}

type pulsarDataIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewPulsarDataIngestionClient(cc grpc.ClientConnInterface) PulsarDataIngestionClient {
	return &pulsarDataIngestionClient{cc}
}

func (c *pulsarDataIngestionClient) Ingest(ctx context.Context, in *Beacons, opts ...grpc.CallOption) (*IngestResult, error) {
	out := new(IngestResult)
	err := c.cc.Invoke(ctx, "/bulkbeacon.PulsarDataIngestion/Ingest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PulsarDataIngestionServer is the server API for PulsarDataIngestion service.
// All implementations must embed UnimplementedPulsarDataIngestionServer
// for forward compatibility
type PulsarDataIngestionServer interface {
	Ingest(context.Context, *Beacons) (*IngestResult, error)
	mustEmbedUnimplementedPulsarDataIngestionServer()
}

// UnimplementedPulsarDataIngestionServer must be embedded to have forward compatible implementations.
type UnimplementedPulsarDataIngestionServer struct {
}

func (UnimplementedPulsarDataIngestionServer) Ingest(context.Context, *Beacons) (*IngestResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedPulsarDataIngestionServer) mustEmbedUnimplementedPulsarDataIngestionServer() {}

// UnsafePulsarDataIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulsarDataIngestionServer will
// result in compilation errors.
type UnsafePulsarDataIngestionServer interface {
	mustEmbedUnimplementedPulsarDataIngestionServer()
}

func RegisterPulsarDataIngestionServer(s grpc.ServiceRegistrar, srv PulsarDataIngestionServer) {
	s.RegisterService(&PulsarDataIngestion_ServiceDesc, srv)
}

func _PulsarDataIngestion_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Beacons)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulsarDataIngestionServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bulkbeacon.PulsarDataIngestion/Ingest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulsarDataIngestionServer).Ingest(ctx, req.(*Beacons))
	}
	return interceptor(ctx, in, info, handler)
}

// PulsarDataIngestion_ServiceDesc is the grpc.ServiceDesc for PulsarDataIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulsarDataIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bulkbeacon.PulsarDataIngestion",
	HandlerType: (*PulsarDataIngestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _PulsarDataIngestion_Ingest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bulkbeacon_v2.proto",
}
